### ISSUE TITLE
Unable to load jdbc-source using Chapter 3

### ISSUE THREAD

**Issue by amodelbello** [Kafka-In-Action-Book/Kafka-In-Action-Source-Code#50]
When running commands listed in the Chapter 3 [Commands.adoc](https://github.com/Kafka-In-Action-Book/Kafka-In-Action-Source-Code/blob/master/KafkaInAction_Chapter3/Commands.adoc) or [Commands.md](https://github.com/Kafka-In-Action-Book/Kafka-In-Action-Source-Code/blob/master/KafkaInAction_Chapter3/Commands.md) I run into the following issue:

```
~/confluent-6.1.1
> confluent local services connect connector load jdbc-source
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

Error: invalid connector: jdbc-source

~/confluent-6.1.1
1 > confluent local services connect connector list
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

Bundled Connectors:
  file-sink
  file-source
  replicator


~/confluent-6.1.1
```

I've tried to install jdbc-source via confluent-hub but it installs it into the `share` directory and I'm afraid I don't know enough yet to make that work.

**Comment by DylanLWScott** [comment]
Hello and thanks for working thru this one @amodelbello!  Can you try with the version at: https://packages.confluent.io/archive/5.5/confluent-5.5.1-2.12.tar.gz?  That version is what was used at the time of writing Chapter 3 and I think has the parts and command format we used in the book. Please let me know if that seems to work better.

**Comment by amodelbello** [comment]
Thanks for the quick response @DylanLWScott !

I installed version 5.5.1 but am now running up against a different error:

```
~
1 > confluent local start
    The local commands are intended for a single-node development environment
    only, NOT for production usage. https://docs.confluent.io/current/cli/index.html

Error: macOS version >= 10.13 is required for all Confluent Platform features to work (detected macOS: 11.6).
Error: exit status 127
```

Any chance we could get a version of the instructions compatible with the 6.2.0 Confluent release?

**Comment by DylanLWScott** [comment]
@amodelbello I see the following: https://github.com/confluentinc/confluent-cli/issues/136 which looks like what you are experiencing.  As per the Chapter 3 instructions, those will remain on the older version since it is about in production. 

However, we can update the Github location for 6.2  if you can verify the following, we can add a section probably.
@daveklein has also said that we will follow up sometime this weekend with more information since he works at Confluent.
Steps to try:  
From,
https://www.confluent.io/hub/confluentinc/kafka-connect-jdbc -> for versions
>confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.2.0
>confluent local services start
>confluent local services connect connector config jdbc-source --config $CONFLUENT_HOME/etc/kafka-connect-jdbc/kafkatest-sqlite.properties &>/dev/null
> confluent local services connect start 
> confluent local services connect connector load jdbc-source

Please let us know if that works or what errors you see then.
Thanks!

**Comment by amodelbello** [comment]
Unfortunately I'm still getting the same error.:

```
> export CONFLUENT_HOME='/Users/adelbello/confluent-6.2.0'

~
> confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.2.0
Running in a "--no-prompt" mode
Implicit acceptance of the license below:
Confluent Community License
https://www.confluent.io/confluent-community-license
Downloading component Kafka Connect JDBC 10.2.0, provided by Confluent, Inc. from Confluent Hub and installing into /Users/adelbello/confluent-6.2.0/share/confluent-hub-components
Implicit confirmation of the question: Do you want to uninstall existing version 10.2.0?
Adding installation directory to plugin path in the following files:
  /Users/adelbello/confluent-6.2.0/etc/kafka/connect-distributed.properties
  /Users/adelbello/confluent-6.2.0/etc/kafka/connect-standalone.properties
  /Users/adelbello/confluent-6.2.0/etc/schema-registry/connect-avro-distributed.properties
  /Users/adelbello/confluent-6.2.0/etc/schema-registry/connect-avro-standalone.properties

Completed

~
> confluent local services start
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT: /var/folders/_p/nvjvl2j571s5l4pvj9xtjcs00000gp/T/confluent.199566
Starting ZooKeeper
ZooKeeper is [UP]
Starting Kafka
Kafka is [UP]
Starting Schema Registry
Schema Registry is [UP]
Starting Kafka REST
Kafka REST is [UP]
Starting Connect
Connect is [UP]
Starting ksqlDB Server
ksqlDB Server is [UP]

~
> confluent local services connect connector config jdbc-source --config $CONFLUENT_HOME/etc/kafka-connect-jdbc/kafkatest-sqlite.properties &>/dev/null

~
1 > confluent local services connect start
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

Using CONFLUENT_CURRENT: /var/folders/_p/nvjvl2j571s5l4pvj9xtjcs00000gp/T/confluent.199566
ZooKeeper is [UP]
Kafka is [UP]
Schema Registry is [UP]
Connect is [UP]

~
> confluent local services connect connector load jdbc-source
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

Error: invalid connector: jdbc-source

~
1 >
```

**Comment by DylanLWScott** [comment]
@sutambe @daveklein Do you know why it says it's invalid? It seems to load the config okay but not sure why we can't load it in version 6.2? The hub install looks like it brings in sqlite and confluent jdbc jar okay?

**Comment by DylanLWScott** [comment]
@amodelbello What do you get when you run: confluent local services connect connector status jdbc-source. If you see a date parse exception- I think we are closer to the real problem

**Comment by amodelbello** [comment]
I get this:
```
1 > confluent local services connect connector status jdbc-source
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

{
  "error_code": 404,
  "message": "No status found for connector jdbc-source"
}

~
>
```

**Comment by amodelbello** [comment]
By the way @DylanLWScott I don't think this is related to my problem but the two "Commands" files in the Chapter 3 directory have different instructions. I'm not sure if that's intentional but I for one am confused by it. the `.adoc` version says to download the enterprise version of confluent and the `.md` version says to download the community version. And from what I can tell the community version of 6.1.1 doesn't have a `confluent` executable. There are other differences too. The `.md` version has the `confluent-hub install confluentinc/kafka-connect-jdbc:10.2.0` command but the `.adoc` version doesn't. Just wanted to point that out in case it was unintentional.

**Comment by DylanLWScott** [comment]
@amodelbello Understnd on the versions. @gAmUssA will be updating at some point. What I would like to try is a couple of things-
For your config file you made-can you put the whole path to your database: ie. connection.url=jdbc:sqlite:/Users/adelbello/confluent-6.2.0kafkatest.db
Next run the command:
> confluent local services connect connector load jdbc-source --config $CONFLUENT_HOME/etc/kafka-connect-jdbc/kafkatest-sqlite.properties
> confluent local services connect connector status jdbc-source

**Comment by amodelbello** [comment]
I get this:
```
~/confluent-6.2.0
> confluent local services connect connector load jdbc-source --config $CONFLUENT_HOME/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/etc/kafkatest-sqlite.properties
confluent local services connect connector status jdbc-source
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

{
  "name": "jdbc-source",
  "config": {
    "connection.url": "jdbc:/Users/adelbello/confluent-6.2.0/kafkatest.db",
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "incrementing.column.name": "id",
    "mode": "incrementing",
    "tasks.max": "1",
    "topic.prefix": "test-sqlite-jdbc-",
    "name": "jdbc-source"
  },
  "tasks": [],
  "type": "source"
}
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

{
  "error_code": 404,
  "message": "No status found for connector jdbc-source"
}

~/confluent-6.2.0
>
```
It's probably important that the 6.2.0 installation does not have an `etc/kafka-connect-jdbc` directory. I'm using the `share/confluent-hub-components/confluentinc-kafka-connect-jdbc/etc/kafkatest-sqlite.properties` which seems analogous. Fwiw I think the 6.1.1 installation _did_ have the `etc/...` directory but I still had the exact same results when running the commands.

**Comment by DylanLWScott** [comment]
@amodelbello Please make sure you connection url has sqlite in it: connection.url=jdbc:sqlite: etc. I didnt see it in your URL.
Then command:
confluent local services connect connector unload jdbc-source
Then command:
> confluent local services connect connector load jdbc-source --config $CONFLUENT_HOME/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/etc/kafkatest-sqlite.properties
Then command:
confluent local services connect connector status jdbc-source

**Comment by amodelbello** [comment]
Looks like that worked!
```
~/confluent-6.2.0
> confluent local services connect connector load jdbc-source --config $CONFLUENT_HOME/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/etc/kafkatest-sqlite.properties
confluent local services connect connector status jdbc-source
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

{
  "name": "jdbc-source",
  "config": {
    "connection.url": "jdbc:sqlite:/Users/adelbello/confluent-6.2.0/kafkatest.db",
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "incrementing.column.name": "id",
    "mode": "incrementing",
    "tasks.max": "1",
    "topic.prefix": "test-sqlite-jdbc-",
    "name": "jdbc-source"
  },
  "tasks": [],
  "type": "source"
}
The local commands are intended for a single-node development environment only,
NOT for production usage. https://docs.confluent.io/current/cli/index.html

{
  "name": "jdbc-source",
  "connector": {
    "state": "RUNNING",
    "worker_id": "127.0.0.1:8083"
  },
  "tasks": [],
  "type": "source"
}

~/confluent-6.2.0
>
```
Missing the sqlite part was a copy paste error when I updated with the full path. I verified by testing again with the relative path and making sure the sqlite string was there and still getting the error.

So the fix is adding the `--config` flag with the properties file path along with specifying the absolute path to the sqlite file within the properties file.

Thanks a lot @DylanLWScott for sticking with me on this! Much appreciated.

**Comment by DylanLWScott** [comment]
@amodelbello Woohoo! Glad we made progress! Since I started this in 2017-lots have changed and sadly we missed updating that section with the newest MEAP versions (seems like a lot has changed with those commands). Please let me know if you are okay with closing this issue or if we need to keep looking at other issues. Thanks!

**Comment by amodelbello** [comment]
Well my issue is definitely solved so I'll close it out. It would be really nice to see the fixes make their way to the Commands files when you're able though :)

**Comment by DylanLWScott** [comment]
Thanks @amodelbello! I added some updates to Commands.md and will have @gAmUssA review if we can go ahead and remove the Commands.adoc file. I have open a different issue open to track that.
